version: "3.8"

services:
  db:
    container_name: ${COMPOSE_PROJECT_NAME}_db
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  admin:
    container_name: ${COMPOSE_PROJECT_NAME}_admin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      VIRTUAL_HOST: ${ADMIN_VIRTUAL_HOST},www.${ADMIN_VIRTUAL_HOST}
      LETSENCRYPT_HOST: ${ADMIN_VIRTUAL_HOST},www.${ADMIN_VIRTUAL_HOST}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - frontend

volumes:
  postgres_data:
  pgadmin_data:

networks:
  frontend:
    external:
      name: nginx-proxy
